### PR TITLE
A pure-python numpy for GAE compatibility 

### PR DESCRIPTION
**Pull request by cmoscardi**
In the event that we're not on GAE, uses numpy.

### CODE REVIEW

**Comment by tianhuil** [comment]
At the risk of redoing work, have you considered this: https://github.com/wadetb/tinynumpy

**Comment by cmoscardi** [comment]
Looks nice! The only immediate issue is it seems to lack the global stats functions ( `np.var` ) , but it's probably better to contribute in to that repo anyway. I'll put a PR up there.

**Comment by tianhuil** [comment]
I would just fork a copy and write code on our own that we merge and offer a PR.

**Comment by cmoscardi** [comment]
As discussed offline - incidentally, most of the functionality I implemented here for our particular needs (operator overloading, global math functions) doesn't exist in tinynumpy. As such, forking would require a bunch more work. This is tested, minimal, and fits what we need as far as a numpy shim goes - so I don't see much sense in rewriting into their codebase. Merging.

**Pull request merged**
