### PR TITLE
Fall back to json if ujson not available

### PR DESCRIPTION
**Pull request by rschroll**
ujson is nice for submission and seeding, since it will serialize numpy arrays and slices.  But it's not necessary on the server at all.

@cmoscardi, @tianhuil: This fellows our email thread.

### CODE REVIEW

**Comment by cmoscardi** [comment]
:+1:

**Comment by rschroll** [comment]
Do we need to up the version for this?

Robert

**Comment by tianhuil** [comment]
If the code changes, you should up the version.

**Comment by cmoscardi** [comment]
Typically you change the version for each stable 'release' you want to make. I'm fine with fixes like this being considered patch versions.

**Comment by chrislerus** [comment]
I will up the version with this and the unicode fix I just added.

**Pull request merged**
